import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const PAGE_CONTENTS = [
  // ===== TRAVEL HAJI UMRAH =====
  {
    page: "travel-haji-umrah",
    section: "hero",
    title: "Travel Haji & Umrah",
    en_title: "Hajj & Umrah Travel",
    content: "Layanan travel haji dan umrah terpercaya dengan pemandu ibadah berpengalaman. Menyediakan paket lengkap mulai dari penerbangan, akomodasi, hingga pembimbingan ibadah di Tanah Suci. Yamindo Travel bekerja sama dengan penyelenggara resmi yang telah memiliki izin dari Kementerian Agama Republik Indonesia, sehingga Anda dapat berangkat dengan tenang dan khusyuk.",
    en_content: "Trusted Hajj and Umrah travel services with experienced worship guides. Providing complete packages from flights, accommodation, to worship guidance in the Holy Land. Yamindo Travel partners with official organizers licensed by the Ministry of Religious Affairs of the Republic of Indonesia, so you can depart with peace of mind and devotion.",
    image: "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/ceecac64eb90.jpg",
    items: JSON.stringify([]),
    en_items: JSON.stringify([]),
    order: 1,
    active: true,
  },
  {
    page: "travel-haji-umrah",
    section: "advantages",
    title: "Mengapa Memilih Kami?",
    en_title: "Why Choose Us?",
    content: "Yamindo Travel hadir dengan layanan profesional dan terpercaya untuk perjalanan ibadah Anda. Dengan pengalaman bertahun-tahun mengantarkan ribuan jamaah ke Tanah Suci, kami memahami setiap kebutuhan dan detail penting perjalanan ibadah Anda. Tim kami terdiri dari muthawwif bersertifikat, operator travel berpengalaman, dan customer service yang siap melayani 24 jam selama perjalanan.",
    en_content: "Yamindo Travel provides professional and trusted services for your worship journey. With years of experience escorting thousands of pilgrims to the Holy Land, we understand every need and important detail of your worship journey. Our team consists of certified muthawwif, experienced travel operators, and customer service ready to serve 24 hours during the journey.",
    items: JSON.stringify([
      { icon: "BadgeCheck", title: "Terdaftar Kemenag", en_title: "Registered with Kemenag", desc: "Izin resmi dari Kementerian Agama RI untuk penyelenggaraan travel haji dan umrah", en_desc: "Official permit from the Ministry of Religious Affairs for hajj and umrah travel" },
      { icon: "Star", title: "Muthawwif Berpengalaman", en_title: "Experienced Muthawwif", desc: "Pemandu ibadah bersertifikat dengan pengalaman puluhan tahun membimbing jamaah", en_desc: "Certified worship guides with decades of experience guiding pilgrims" },
      { icon: "Hotel", title: "Hotel Strategis", en_title: "Strategic Hotels", desc: "Akomodasi bintang 3-4 dengan jarak berjalan kaki ke Masjidil Haram dan Masjid Nabawi", en_desc: "3-4 star accommodation within walking distance to Masjidil Haram and Masjid Nabawi" },
      { icon: "Headphones", title: "Layanan 24 Jam", en_title: "24-Hour Service", desc: "Tim support siap membantu jamaah selama 24 jam selama di Tanah Suci", en_desc: "Support team ready to assist pilgrims 24 hours during their stay in the Holy Land" },
    ]),
    en_items: JSON.stringify([
      { icon: "BadgeCheck", title: "Registered with Kemenag", en_title: "Registered with Kemenag", desc: "Official permit from the Ministry of Religious Affairs for hajj and umrah travel", en_desc: "Official permit from the Ministry of Religious Affairs for hajj and umrah travel" },
      { icon: "Star", title: "Experienced Muthawwif", en_title: "Experienced Muthawwif", desc: "Certified worship guides with decades of experience guiding pilgrims", en_desc: "Certified worship guides with decades of experience guiding pilgrims" },
      { icon: "Hotel", title: "Strategic Hotels", en_title: "Strategic Hotels", desc: "3-4 star accommodation within walking distance to Masjidil Haram and Masjid Nabawi", en_desc: "3-4 star accommodation within walking distance to Masjidil Haram and Masjid Nabawi" },
      { icon: "Headphones", title: "24-Hour Service", en_title: "24-Hour Service", desc: "Support team ready to assist pilgrims 24 hours during their stay in the Holy Land", en_desc: "Support team ready to assist pilgrims 24 hours during their stay in the Holy Land" },
    ]),
    order: 2,
    active: true,
  },
  {
    page: "travel-haji-umrah",
    section: "packages",
    title: "Paket Travel Kami",
    en_title: "Our Travel Packages",
    content: "Pilih paket perjalanan ibadah yang sesuai dengan kebutuhan dan budget Anda. Setiap paket telah dirancang dengan teliti untuk memastikan kenyamanan dan kelancaran ibadah Anda di Tanah Suci. Kami menawarkan berbagai pilihan mulai dari paket hemat hingga paket eksekutif, semua dengan standar pelayanan terbaik.",
    en_content: "Choose the worship travel package that suits your needs and budget. Each package has been carefully designed to ensure your comfort and smooth worship in the Holy Land. We offer various options from budget-friendly to executive packages, all with the best service standards.",
    items: JSON.stringify([]),
    en_items: JSON.stringify([]),
    order: 3,
    active: true,
  },
  {
    page: "travel-haji-umrah",
    section: "gallery",
    title: "Dokumentasi Perjalanan",
    en_title: "Journey Documentation",
    content: "",
    en_content: "",
    image: "",
    items: JSON.stringify(["https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/10f5367ad7e3.jpg", "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/588394332193.jpg", "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/ceecac64eb90.jpg"]),
    en_items: JSON.stringify([]),
    order: 4,
    active: true,
  },
  {
    page: "travel-haji-umrah",
    section: "cta",
    title: "Wujudkan Rencana Ibadah Anda",
    en_title: "Fulfill Your Worship Plan",
    content: "Hubungi kami sekarang untuk konsultasi gratis dan dapatkan penawaran terbaik untuk perjalanan haji dan umrah Anda. Tim kami siap membantu Anda dari proses pendaftaran hingga kembali ke Tanah Air dengan selamat. Jangan tunda lagi, rencanakan perjalanan ibadah impian Anda bersama Yamindo Travel.",
    en_content: "Contact us now for a free consultation and get the best offers for your hajj and umrah journey. Our team is ready to help you from registration until you return home safely. Don't delay, plan your dream worship journey with Yamindo Travel.",
    items: JSON.stringify([]),
    en_items: JSON.stringify([]),
    order: 5,
    active: true,
  },

  // ===== AQIQAH =====
  {
    page: "aqiqah",
    section: "hero",
    title: "Layanan Aqiqah",
    en_title: "Aqiqah Service",
    content: "Layanan aqiqah lengkap dan syar'i. Kami menyediakan hewan aqiqah berkualitas, penyembelihan sesuai tata cara Islam, hingga distribusi daging ke yang berhak. Seluruh proses dilaksanakan oleh petugas yang kompeten dan berpengalaman, memastikan setiap rangkaian aqiqah berjalan sesuai dengan ketentuan syariat Islam. Kami juga mendokumentasikan proses penyembelihan sebagai bukti dan kenang-kenangan bagi keluarga.",
    en_content: "Complete and sharia-compliant aqiqah service. We provide quality aqiqah animals, Islamic slaughter procedures, and meat distribution to rightful recipients. The entire process is carried out by competent and experienced officers, ensuring every aqiqah sequence proceeds according to Islamic sharia provisions. We also document the slaughter process as proof and memento for the family.",
    image: "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/f3f9ca9967e5.jpg",
    items: JSON.stringify([]),
    en_items: JSON.stringify([]),
    order: 1,
    active: true,
  },
  {
    page: "aqiqah",
    section: "advantages",
    title: "Keunggulan Layanan Kami",
    en_title: "Our Service Advantages",
    content: "Yamindo Aqiqah mengutamakan kualitas dan kesesuaian syariat dalam setiap layanan. Hewan aqiqah kami dipilih langsung dengan kriteria sehat, gemuk, dan memenuhi syarat yang ditentukan oleh ulama. Proses penyembelihan dilakukan oleh penyembelih yang berpengalaman dengan membaca doa dan niat yang benar. Kami juga menyediakan layanan antar ke lokasi sehingga Anda tidak perlu repot.",
    en_content: "Yamindo Aqiqah prioritizes quality and sharia compliance in every service. Our aqiqah animals are selected directly with healthy, plump criteria meeting the requirements determined by scholars. The slaughter process is performed by experienced slaughterers with correct prayers and intentions. We also provide delivery service to your location so you don't need to worry.",
    items: JSON.stringify([
      { icon: "Shield", title: "Syar'i & Terpercaya", en_title: "Sharia-Compliant & Trusted", desc: "Penyembelihan mengikuti tata cara Islam dengan doa dan niat yang benar", en_desc: "Slaughtered following Islamic procedures with correct prayers and intentions" },
      { icon: "Award", title: "Hewan Sehat & Berkualitas", en_title: "Healthy & Quality Animals", desc: "Kambing dan sapi dipilih langsung dengan kriteria sehat, gemuk, dan sesuai syarat", en_desc: "Goats and cows are selected directly with healthy, plump criteria meeting requirements" },
      { icon: "Truck", title: "Antar ke Lokasi", en_title: "Delivery to Location", desc: "Kami antar daging aqiqah ke rumah Anda atau salurkan ke panti asuhan yang membutuhkan", en_desc: "We deliver aqiqah meat to your home or distribute to orphanages in need" },
      { icon: "Camera", title: "Dokumentasi Foto/Video", en_title: "Photo/Video Documentation", desc: "Setiap proses penyembelihan didokumentasikan dan dikirimkan kepada Anda sebagai bukti", en_desc: "Every slaughter process is documented and sent to you as proof" },
    ]),
    en_items: JSON.stringify([
      { icon: "Shield", title: "Sharia-Compliant & Trusted", desc: "Slaughtered following Islamic procedures with correct prayers and intentions" },
      { icon: "Award", title: "Healthy & Quality Animals", desc: "Goats and cows are selected directly with healthy, plump criteria meeting requirements" },
      { icon: "Truck", title: "Delivery to Location", desc: "We deliver aqiqah meat to your home or distribute to orphanages in need" },
      { icon: "Camera", title: "Photo/Video Documentation", desc: "Every slaughter process is documented and sent to you as proof" },
    ]),
    order: 2,
    active: true,
  },
  {
    page: "aqiqah",
    section: "packages",
    title: "Paket Aqiqah Kami",
    en_title: "Our Aqiqah Packages",
    content: "Tersedia berbagai pilihan paket aqiqah yang dapat disesuaikan dengan kebutuhan Anda. Mulai dari paket kambing satuan, paket sapi untuk kelompok, hingga paket lengkap dengan nasi box siap saji. Semua paket sudah termasuk proses penyembelihan, pendistribusian daging, dan dokumentasi lengkap.",
    en_content: "Various aqiqah package options are available to suit your needs. From individual goat packages, cow packages for groups, to complete packages with ready-to-serve rice boxes. All packages include the slaughter process, meat distribution, and complete documentation.",
    items: JSON.stringify([]),
    en_items: JSON.stringify([]),
    order: 3,
    active: true,
  },
  {
    page: "aqiqah",
    section: "process",
    title: "Alur Pemesanan Aqiqah",
    en_title: "Aqiqah Ordering Process",
    content: "Proses pemesanan aqiqah di Yamindo sangat mudah dan transparan. Anda cukup menghubungi kami, memilih paket, melakukan pembayaran, dan kami akan menangani sisanya. Setiap tahap dilaporkan kepada Anda sehingga Anda bisa memantau progres pemesanan aqiqah dari awal hingga selesai.",
    en_content: "The aqiqah ordering process at Yamindo is very easy and transparent. Simply contact us, choose a package, make a payment, and we will handle the rest. Each stage is reported to you so you can monitor the progress of your aqiqah order from start to finish.",
    items: JSON.stringify([
      { step: "01", title: "Hubungi Kami", en_title: "Contact Us", desc: "Pilih paket dan informasikan nama, tanggal, dan alamat pengantaran", en_desc: "Choose a package and provide name, date, and delivery address" },
      { step: "02", title: "Pembayaran", en_title: "Payment", desc: "Lakukan pembayaran via transfer bank atau metode lain yang tersedia", en_desc: "Make payment via bank transfer or other available methods" },
      { step: "03", title: "Proses Aqiqah", en_title: "Aqiqah Process", desc: "Penyembelihan dilakukan sesuai syariat dengan dokumentasi lengkap", en_desc: "Slaughter is performed according to sharia with full documentation" },
      { step: "04", title: "Pengantaran", en_title: "Delivery", desc: "Daging diantar ke lokasi Anda atau disalurkan ke panti asuhan", en_desc: "Meat is delivered to your location or distributed to orphanages" },
    ]),
    en_items: JSON.stringify([
      { step: "01", title: "Contact Us", desc: "Choose a package and provide name, date, and delivery address" },
      { step: "02", title: "Payment", desc: "Make payment via bank transfer or other available methods" },
      { step: "03", title: "Aqiqah Process", desc: "Slaughter is performed according to sharia with full documentation" },
      { step: "04", title: "Delivery", desc: "Meat is delivered to your location or distributed to orphanages" },
    ]),
    order: 4,
    active: true,
  },
  {
    page: "aqiqah",
    section: "gallery",
    title: "Dokumentasi Aqiqah",
    en_title: "Aqiqah Documentation",
    content: "",
    en_content: "",
    image: "",
    items: JSON.stringify(["https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/7dd3d55d5905.jpg", "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/56fd7489e7a7.jpg", "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/f3f9ca9967e5.jpg"]),
    en_items: JSON.stringify([]),
    order: 5,
    active: true,
  },
  {
    page: "aqiqah",
    section: "cta",
    title: "Segerakan Aqiqah Buah Hati Anda",
    en_title: "Perform Aqiqah for Your Child",
    content: "Kami siap membantu Anda melaksanakan aqiqah yang syar'i dan praktis. Hubungi kami sekarang untuk konsultasi dan pemesanan. Aqiqah adalah sunnah Nabi Muhammad SAW yang dianjurkan untuk dilaksanakan pada hari ketujuh kelahiran anak. Dengan Yamindo, ibadah aqiqah buah hati Anda akan terlaksana dengan lancar dan penuh keberkahan.",
    en_content: "We are ready to help you perform a sharia-compliant and practical aqiqah. Contact us now for consultation and ordering. Aqiqah is a sunnah of Prophet Muhammad SAW recommended to be performed on the seventh day of a child's birth. With Yamindo, your child's aqiqah will be carried out smoothly and with full blessings.",
    items: JSON.stringify([]),
    en_items: JSON.stringify([]),
    order: 6,
    active: true,
  },

  // ===== PELATIHAN AGENCY =====
  {
    page: "pelatihan-agency",
    section: "hero",
    title: "Pelatihan & Agency Digital Marketing",
    en_title: "Digital Marketing Training & Agency",
    content: "Tingkatkan kehadiran digital bisnis Anda melalui pelatihan praktis dan jasa digital marketing profesional. Dari social media, SEO, hingga iklan digital. Yamindo Digital Marketing hadir sebagai solusi lengkap bagi UMKM, startup, dan perusahaan yang ingin meningkatkan brand awareness dan penjualan melalui kanal digital. Tim kami terdiri dari praktisi digital marketing yang berpengalaman di berbagai industri.",
    en_content: "Boost your business digital presence through practical training and professional digital marketing services. From social media, SEO, to digital advertising. Yamindo Digital Marketing presents as a complete solution for SMEs, startups, and companies looking to increase brand awareness and sales through digital channels. Our team consists of experienced digital marketing practitioners across various industries.",
    image: "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/093ed46fc4df.jpg",
    items: JSON.stringify([]),
    en_items: JSON.stringify([]),
    order: 1,
    active: true,
  },
  {
    page: "pelatihan-agency",
    section: "stats",
    title: "Pencapaian Kami",
    en_title: "Our Achievements",
    content: "Dengan pengalaman bertahun-tahun di industri digital marketing, kami telah membantu ratusan bisnis dari berbagai sektor untuk tumbuh dan berkembang di dunia digital. Komitmen kami adalah memberikan hasil nyata yang terukur untuk setiap klien.",
    en_content: "With years of experience in the digital marketing industry, we have helped hundreds of businesses from various sectors grow and develop in the digital world. Our commitment is to deliver measurable real results for every client.",
    items: JSON.stringify([
      { num: "500+", label: "Klien Terlayani", en_label: "Clients Served" },
      { num: "1000+", label: "Peserta Pelatihan", en_label: "Training Participants" },
      { num: "50+", label: "Brand Dikelola", en_label: "Brands Managed" },
      { num: "98%", label: "Tingkat Kepuasan", en_label: "Satisfaction Rate" },
    ]),
    en_items: JSON.stringify([
      { num: "500+", label: "Clients Served" },
      { num: "1000+", label: "Training Participants" },
      { num: "50+", label: "Brands Managed" },
      { num: "98%", label: "Satisfaction Rate" },
    ]),
    order: 2,
    active: true,
  },
  {
    page: "pelatihan-agency",
    section: "services",
    title: "Jasa Digital Marketing",
    en_title: "Digital Marketing Services",
    content: "Kami membantu bisnis Anda tumbuh melalui strategi digital marketing yang terukur dan berbasis data. Setiap layanan dirancang sesuai dengan kebutuhan unik bisnis Anda, dengan fokus pada ROI dan pertumbuhan jangka panjang. Tim kami akan menganalisis kondisi bisnis Anda, menyusun strategi yang tepat, dan mengeksekusinya secara konsisten.",
    en_content: "We help your business grow through measurable and data-driven digital marketing strategies. Each service is designed according to your business's unique needs, with focus on ROI and long-term growth. Our team will analyze your business conditions, formulate the right strategy, and execute it consistently.",
    items: JSON.stringify([
      { icon: "Megaphone", title: "Social Media Management", desc: "Pengelolaan akun sosial media secara profesional. Kami buat konten, jadwal posting, dan interaksi dengan audiens Anda agar brand semakin dikenal dan engagement meningkat pesat.", en_desc: "Professional social media account management. We create content, schedule posts, and engage with your audience to increase brand awareness and boost engagement significantly." },
      { icon: "Target", title: "Digital Advertising", desc: "Iklan digital yang terukur dan efisien. Kami kelola kampanye Google Ads, Meta Ads, dan TikTok Ads dengan optimasi berkelanjutan untuk mendapatkan ROI terbaik.", en_desc: "Measurable and efficient digital advertising. We manage Google Ads, Meta Ads, and TikTok Ads campaigns with continuous optimization for the best ROI." },
      { icon: "PenTool", title: "Content Creation", desc: "Pembuatan konten berkualitas tinggi berupa foto, video pendek, desain grafis, dan copywriting yang menarik disesuaikan dengan identitas brand Anda.", en_desc: "High-quality content creation including photos, short videos, graphic design, and compelling copywriting tailored to your brand identity." },
      { icon: "Search", title: "SEO & Website", desc: "Optimasi mesin pencari agar website Anda muncul di halaman pertama Google. Kami juga menyediakan jasa pembuatan website modern dan SEO-friendly.", en_desc: "Search engine optimization to get your website on Google's first page. We also provide modern and SEO-friendly website creation services." },
      { icon: "BarChart3", title: "Analytics & Reporting", desc: "Laporan bulanan yang detail dan transparan. Kami pantau semua metrik penting dan berikan rekomendasi strategis berdasarkan data.", en_desc: "Detailed and transparent monthly reports. We monitor all key metrics and provide data-driven strategic recommendations." },
      { icon: "MonitorSmartphone", title: "Brand Strategy", desc: "Rancang strategi brand yang kuat dan konsisten, mulai dari positioning, brand voice, visual identity, hingga go-to-market strategy.", en_desc: "Design a strong and consistent brand strategy, from positioning, brand voice, visual identity, to go-to-market strategy." },
    ]),
    en_items: JSON.stringify([
      { icon: "Megaphone", title: "Social Media Management", desc: "Professional social media account management with content creation, scheduling, and audience engagement." },
      { icon: "Target", title: "Digital Advertising", desc: "Measurable and efficient digital advertising across Google Ads, Meta Ads, and TikTok Ads." },
      { icon: "PenTool", title: "Content Creation", desc: "High-quality content creation including photos, short videos, graphic design, and copywriting." },
      { icon: "Search", title: "SEO & Website", desc: "Search engine optimization and modern, SEO-friendly website creation services." },
      { icon: "BarChart3", title: "Analytics & Reporting", desc: "Detailed and transparent monthly reports with data-driven strategic recommendations." },
      { icon: "MonitorSmartphone", title: "Brand Strategy", desc: "Strong and consistent brand strategy from positioning to go-to-market." },
    ]),
    order: 3,
    active: true,
  },
  {
    page: "pelatihan-agency",
    section: "training",
    title: "Program Pelatihan",
    en_title: "Training Programs",
    content: "Pelatihan praktis dengan instruktur berpengalaman. Sertifikat diberikan setelah menyelesaikan program. Setiap program pelatihan dirancang dengan kurikulum yang relevan dengan kebutuhan industri saat ini, sehingga peserta langsung bisa menerapkan ilmunya di dunia kerja atau bisnis mereka.",
    en_content: "Practical training with experienced instructors. Certificate provided upon program completion. Each training program is designed with a curriculum relevant to current industry needs, so participants can immediately apply their knowledge in the workplace or their business.",
    items: JSON.stringify([]),
    en_items: JSON.stringify([]),
    order: 4,
    active: true,
  },
  {
    page: "pelatihan-agency",
    section: "gallery",
    title: "Kegiatan Kami",
    en_title: "Our Activities",
    content: "",
    en_content: "",
    image: "",
    items: JSON.stringify(["https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/263b18036fa5.jpg", "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/cbc03782aa60.jpg", "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/093ed46fc4df.jpg"]),
    en_items: JSON.stringify([]),
    order: 5,
    active: true,
  },
  {
    page: "pelatihan-agency",
    section: "cta",
    title: "Siap Mendigitalisasi Bisnis Anda?",
    en_title: "Ready to Digitalize Your Business?",
    content: "Konsultasikan kebutuhan digital marketing bisnis Anda secara gratis. Tim kami siap membantu Anda meraih target. Baik Anda baru memulai atau ingin meningkatkan performa digital yang sudah ada, kami memiliki solusi yang tepat untuk setiap tahap perjalanan digital bisnis Anda.",
    en_content: "Consult your business digital marketing needs for free. Our team is ready to help you achieve your targets. Whether you're just starting or want to improve existing digital performance, we have the right solution for every stage of your business digital journey.",
    items: JSON.stringify([]),
    en_items: JSON.stringify([]),
    order: 6,
    active: true,
  },

  // ===== KONTAK =====
  {
    page: "kontak",
    section: "hero",
    title: "Kontak Kami",
    en_title: "Get In Touch",
    content: "Kami siap mendengar pertanyaan, saran, dan masukan Anda. Jangan ragu untuk menghubungi kami melalui formulir di bawah, telepon, email, atau kunjungi langsung kantor kami. Tim Yamindo selalu terbuka untuk berkomunikasi dengan para donatur, mitra, dan masyarakat umum. Kami percaya bahwa komunikasi yang baik adalah kunci kerjasama yang produktif dan berkelanjutan.",
    en_content: "We are ready to hear your questions, suggestions, and feedback. Don't hesitate to contact us through the form below, phone, email, or visit our office directly. The Yamindo team is always open to communicating with donors, partners, and the general public. We believe that good communication is the key to productive and sustainable cooperation.",
    image: "https://images.unsplash.com/photo-1423666639041-f56000c27a9a?w=1600&q=80",
    items: JSON.stringify([]),
    en_items: JSON.stringify([]),
    order: 1,
    active: true,
  },
  {
    page: "kontak",
    section: "form",
    title: "Ada pertanyaan? Tulis kepada kami",
    en_title: "Have a question? Write to us",
    content: "Isi formulir di bawah ini dan tim kami akan merespons sesegera mungkin. Kami berkomitmen untuk membalas setiap pesan dalam waktu 1x24 jam kerja. Jangan ragu untuk bertanya tentang program donasi, layanan usaha, atau hal lainnya seputar Yayasan Yasir Amin Indonesia.",
    en_content: "Fill in the form below and our team will respond as soon as possible. We are committed to replying to every message within 1x24 business hours. Don't hesitate to ask about donation programs, business services, or anything else about Yasir Amin Indonesia Foundation.",
    items: JSON.stringify([]),
    en_items: JSON.stringify([]),
    order: 2,
    active: true,
  },

  // ===== LAYANAN =====
  {
    page: "layanan",
    section: "hero",
    title: "Layanan Kami",
    en_title: "Our Services",
    content: "Yayasan Yasir Amin Indonesia menyediakan berbagai layanan yang berfokus pada pendidikan, pemberdayaan masyarakat, dan dakwah Islam. Setiap layanan dirancang untuk memberikan dampak positif yang nyata bagi masyarakat, terutama dalam bidang pendidikan Al-Quran, kesehatan, dan pengembangan ekonomi umat. Kami berkomitmen untuk terus berinovasi dalam menghadirkan layanan yang berkualitas dan bermanfaat.",
    en_content: "Yasir Amin Indonesia Foundation provides various services focused on education, community empowerment, and Islamic da'wah. Each service is designed to create a real positive impact on society, especially in Al-Quran education, health, and Islamic economic development. We are committed to continuously innovating to deliver quality and beneficial services.",
    items: JSON.stringify([]),
    en_items: JSON.stringify([]),
    order: 1,
    active: true,
  },
  {
    page: "layanan",
    section: "stats",
    title: "Layanan Kami dalam Angka",
    en_title: "Our Services in Numbers",
    content: "Dengan pengalaman bertahun-tahun melayani masyarakat, kami terus berkembang dan memperluas jangkauan layanan ke berbagai wilayah di Indonesia.",
    en_content: "With years of experience serving the community, we continue to grow and expand our service reach to various regions in Indonesia.",
    items: JSON.stringify([
      { num: "8", label: "Layanan Inti", en_label: "Core Services" },
      { num: "30+", label: "Provinsi", en_label: "Provinces" },
      { num: "5000+", label: "Penerima Manfaat", en_label: "Beneficiaries" },
      { num: "100+", label: "Relawan", en_label: "Volunteers" },
    ]),
    en_items: JSON.stringify([
      { num: "8", label: "Core Services" },
      { num: "30+", label: "Provinces" },
      { num: "5000+", label: "Beneficiaries" },
      { num: "100+", label: "Volunteers" },
    ]),
    order: 2,
    active: true,
  },
  {
    page: "layanan",
    section: "cta",
    title: "Butuh Layanan Kami?",
    en_title: "Need Our Services?",
    content: "Hubungi kami untuk informasi lebih lanjut tentang layanan yang tersedia. Kami siap membantu Anda dengan sepenuh hati dan profesionalisme tinggi. Setiap konsultasi kami berikan secara gratis tanpa komitmen.",
    en_content: "Contact us for more information about available services. We are ready to help you with full dedication and high professionalism. Every consultation we provide is free of charge and without commitment.",
    items: JSON.stringify([]),
    en_items: JSON.stringify([]),
    order: 3,
    active: true,
  },

  // ===== PROGRAM =====
  {
    page: "program",
    section: "hero",
    title: "Program Donasi",
    en_title: "Donation Programs",
    content: "Yayasan Yasir Amin Indonesia mengelola berbagai program donasi yang tersebar di berbagai sektor. Setiap program dirancang untuk memberikan dampak sosial yang maksimal dan terukur. Dari program pendidikan Al-Quran hingga pemberdayaan ekonomi masyarakat, dari bantuan kesehatan hingga program santunan anak yatim. Kami memastikan setiap donasi yang Anda berikan sampai kepada penerima manfaat yang tepat dengan pelaporan yang transparan.",
    en_content: "Yasir Amin Indonesia Foundation manages various donation programs across multiple sectors. Each program is designed to provide maximum and measurable social impact. From Al-Quran education programs to community economic empowerment, from health assistance to orphan support programs. We ensure every donation you give reaches the right beneficiaries with transparent reporting.",
    items: JSON.stringify([]),
    en_items: JSON.stringify([]),
    order: 1,
    active: true,
  },
  {
    page: "program",
    section: "stats",
    title: "Dampak Donasi Anda",
    en_title: "Your Donation Impact",
    content: "Bersama para donatur yang dermawan, kami terus bergerak untuk menghadirkan perubahan nyata di masyarakat. Setiap rupiah yang disumbangkan memiliki arti besar bagi kehidupan banyak orang.",
    en_content: "Together with generous donors, we continue to strive to create real change in society. Every rupiah donated has great meaning for the lives of many people.",
    items: JSON.stringify([
      { num: "Rp 20.7M", label: "Terkumpul", en_label: "Raised" },
      { num: "8", label: "Program Aktif", en_label: "Active Programs" },
      { num: "15K+", label: "Donatur", en_label: "Donors" },
      { num: "500+", label: "Penerima Manfaat", en_label: "Beneficiaries" },
    ]),
    en_items: JSON.stringify([
      { num: "Rp 20.7M", label: "Raised" },
      { num: "8", label: "Active Programs" },
      { num: "15K+", label: "Donors" },
      { num: "500+", label: "Beneficiaries" },
    ]),
    order: 2,
    active: true,
  },

  // ===== TENTANG =====
  {
    page: "tentang",
    section: "hero",
    title: "Tentang Kami",
    en_title: "About Us",
    content: "Yayasan Yasir Amin Indonesia (YAMINDO) adalah organisasi nirlaba yang berkomitmen untuk meningkatkan kualitas pendidikan, pemberdayaan masyarakat, dan dakwah Islam di Indonesia. Didirikan dengan semangat untuk menciptakan generasi yang berilmu, berakhlak mulia, dan bermanfaat bagi sesama. Kami percaya bahwa pendidikan adalah kunci untuk mengubah masa depan bangsa.",
    en_content: "Yasir Amin Indonesia Foundation (YAMINDO) is a non-profit organization committed to improving the quality of education, community empowerment, and Islamic da'wah in Indonesia. Founded with the spirit of creating a generation that is knowledgeable, of noble character, and beneficial to others. We believe that education is the key to changing the future of the nation.",
    items: JSON.stringify([]),
    en_items: JSON.stringify([]),
    order: 1,
    active: true,
  },

  // ===== BERITA =====
  {
    page: "berita",
    section: "hero",
    title: "Berita & Artikel",
    en_title: "News & Articles",
    content: "Ikuti berita terbaru, artikel inspiratif, dan update kegiatan Yayasan Yasir Amin Indonesia. Kami menyajikan informasi yang berguna seputar program donasi, kegiatan sosial, tips pendidikan, dan berbagai artikel menarik lainnya yang relevan dengan misi dan visi kami dalam membangun masyarakat yang lebih baik.",
    en_content: "Follow the latest news, inspiring articles, and updates on Yasir Amin Indonesia Foundation activities. We present useful information about donation programs, social activities, education tips, and various other interesting articles relevant to our mission and vision in building a better society.",
    items: JSON.stringify([]),
    en_items: JSON.stringify([]),
    order: 1,
    active: true,
  },

  // ===== GALERI =====
  {
    page: "galeri",
    section: "hero",
    title: "Galeri Kegiatan",
    en_title: "Activity Gallery",
    content: "Dokumentasi visual kegiatan dan program Yayasan Yasir Amin Indonesia. Melalui galeri ini, Anda dapat melihat langsung berbagai kegiatan yang telah kami laksanakan, mulai dari pembagian santunan, pelatihan masyarakat, kegiatan pendidikan Al-Quran, hingga dokumentasi perjalanan ibadah haji dan umrah. Setiap foto dan video menceritakan kisah nyata tentang dampak positif yang kita ciptakan bersama.",
    en_content: "Visual documentation of Yasir Amin Indonesia Foundation activities and programs. Through this gallery, you can directly see various activities we have carried out, from charity distribution, community training, Al-Quran education activities, to hajj and umrah worship journey documentation. Each photo and video tells a real story about the positive impact we create together.",
    items: JSON.stringify([]),
    en_items: JSON.stringify([]),
    order: 1,
    active: true,
  },

  // ===== TIM =====
  {
    page: "tim",
    section: "hero",
    title: "Tim Kami",
    en_title: "Our Team",
    content: "Kenali lebih dekat tim di balik Yayasan Yasir Amin Indonesia. Kami terdiri dari profesional yang berdedikasi dan berpengalaman di bidangnya masing-masing, bersatu dengan satu tujuan yang sama: menciptakan dampak positif bagi masyarakat Indonesia melalui pendidikan, pemberdayaan, dan dakwah Islam.",
    en_content: "Get to know the team behind Yasir Amin Indonesia Foundation. We consist of dedicated and experienced professionals in their respective fields, united with one common goal: creating positive impact for Indonesian society through education, empowerment, and Islamic da'wah.",
    items: JSON.stringify([]),
    en_items: JSON.stringify([]),
    order: 1,
    active: true,
  },

  // ===== BERANDA =====
  {
    page: "beranda",
    section: "intro",
    title: "Mengenal YAMINDO",
    en_title: "About YAMINDO",
    content: "Yayasan Yasir Amin Indonesia adalah lembaga yang bergerak di bidang pendidikan Al-Quran, pemberdayaan masyarakat, dan dakwah Islam. Dengan semangat ukhuwah islamiyah, kami berkomitmen untuk menyebarkan kebaikan dan membantu sesama melalui berbagai program yang terukur dan berkelanjutan. Kami mengelola dana donasi dengan amanah dan transparan, memastikan setiap rupiah yang Anda sumbangkan tepat sasaran.",
    en_content: "Yasir Amin Indonesia Foundation is an institution engaged in Al-Quran education, community empowerment, and Islamic da'wah. With the spirit of Islamic brotherhood, we are committed to spreading goodness and helping others through various measurable and sustainable programs. We manage donation funds with trust and transparency, ensuring every rupiah you donate reaches its intended purpose.",
    items: JSON.stringify([]),
    en_items: JSON.stringify([]),
    order: 1,
    active: true,
  },
];

async function main() {
  console.log("Seeding PageContent...");

  // Clear existing
  await prisma.pageContent.deleteMany({});

  for (const item of PAGE_CONTENTS) {
    await prisma.pageContent.create({ data: item });
    console.log(`  Created: ${item.page}/${item.section} - ${item.title}`);
  }

  console.log(`\nDone! ${PAGE_CONTENTS.length} PageContent records seeded.`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
