import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

async function main() {
  // Add more news articles
  const extraNews = [
    { id: 'news-7', slug: 'rumah-sakit-wakaf', title: 'Pembangunan Rumah Sakit Wakaf Tahap Pertama Dimulai', en_title: 'First Phase of Waqf Hospital Construction Begins', category: 'Wakaf', en_category: 'Waqf', content: 'Pembangunan rumah sakit wakaf pertama Yamindo resmi dimulai di Kabupaten Garut, Jawa Barat. Fasilitas kesehatan berkapasitas 100 tempat tidur ini akan melayani masyarakat kurang mampu secara gratis. Pembangunan tahap pertama mencakup gedung utama dan instalasi medis dasar. Target operasional penuh di tahun 2028.', en_content: 'The construction of Yamindo first waqf hospital has officially begun in Garut Regency, West Java. The 100-bed healthcare facility will serve underprivileged communities for free. The first phase construction includes the main building and basic medical installations. Full operational target by 2028.', excerpt: 'Rumah sakit wakaf berkapasitas 100 tempat tidur mulai dibangun di Garut.', en_excerpt: '100-bed waqf hospital construction begins in Garut.', image: 'https://images.unsplash.com/photo-1586773860418-d37222d8fce3?w=800&q=80', author: 'Tim Media Yamindo', date: '5 Juni 2026', featured: false },
    { id: 'news-8', slug: 'klinik-keliling-jakarta', title: 'Klinik Keliling Yamindo Jangkau 100 Ribu Warga Jakarta', en_title: 'Yamindo Mobile Clinics Reach 100 Thousand Jakarta Residents', category: 'Kesehatan', en_category: 'Healthcare', content: 'Program klinik keliling Yamindo telah berhasil menjangkau lebih dari 100.000 warga Jakarta dalam satu tahun terakhir. Layanan yang diberikan meliputi pemeriksaan kesehatan gratis, pemberian obat, imunisasi anak, dan konsultasi gizi. Program ini beroperasi setiap akhir pekan di berbagai kelurahan di Jakarta.', en_content: 'Yamindo mobile clinic program has successfully reached more than 100,000 Jakarta residents in the past year. Services provided include free health check-ups, medicine distribution, child immunization, and nutrition consultation. The program operates every weekend in various sub-districts in Jakarta.', excerpt: 'Program klinik keliling telah menjangkau 100 ribu warga Jakarta.', en_excerpt: 'Mobile clinic program has reached 100 thousand Jakarta residents.', image: 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?w=800&q=80', author: 'Tim Media Yamindo', date: '28 Mei 2026', featured: false },
    { id: 'news-9', slug: 'pelatihan-guru-daerah-terpencil', title: 'Pelatihan 200 Guru di Daerah Terpencil Indonesia Timur', en_title: 'Training 200 Teachers in Remote Areas of Eastern Indonesia', category: 'Pendidikan', en_category: 'Education', content: 'Yamindo menyelenggarakan pelatihan guru selama 2 minggu untuk 200 guru dari daerah terpencil di Papua, Maluku, dan NTT. Pelatihan mencakup metode pengajaran modern, penggunaan teknologi dalam pembelajaran, dan manajemen kelas. Setiap peserta juga menerima paket peralatan mengajar lengkap.', en_content: 'Yamindo organized a 2-week teacher training for 200 teachers from remote areas in Papua, Maluku, and NTT. The training covers modern teaching methods, technology in learning, and classroom management. Each participant also receives a complete teaching equipment package.', excerpt: '200 guru dari daerah terpencil mengikuti pelatihan intensif.', en_excerpt: '200 teachers from remote areas attend intensive training.', image: 'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=800&q=80', author: 'Tim Media Yamindo', date: '20 Mei 2026', featured: false },
  ];
  for (const n of extraNews) await prisma.newsArticle.upsert({ where: { id: n.id }, update: n, create: n });

  // Add more team members (to have more on the page)
  const extraTeam = [
    { id: 'team-5', name: 'Ir. Siti Aminah, M.Sc.', en_name: 'Ir. Siti Aminah, M.Sc.', role: 'Koordinator Pendidikan', en_role: 'Education Coordinator', bio: 'Memimpin seluruh program pendidikan Yamindo dengan pengalaman 15 tahun di bidang pengembangan kurikulum dan manajemen sekolah.', en_bio: 'Leads all Yamindo education programs with 15 years of experience in curriculum development and school management.', image: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400&q=80', active: true },
    { id: 'team-6', name: 'dr. Ahmad Fadli, Sp.PD.', en_name: 'dr. Ahmad Fadli, Sp.PD.', role: 'Koordinator Kesehatan', en_role: 'Healthcare Coordinator', bio: 'Dokter spesialis penyakit dalam yang memimpin program kesehatan dan layanan ambulan gratis Yamindo sejak 2021.', en_bio: 'An internal medicine specialist who has led Yamindo healthcare programs and free ambulance services since 2021.', image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=400&q=80', active: true },
    { id: 'team-7', name: 'Hj. Rina Sulistyowati, S.E.', en_name: 'Hj. Rina Sulistyowati, S.E.', role: 'Koordinator Zakat & Wakaf', en_role: 'Zakat & Waqf Coordinator', bio: 'Ahli dalam pengelolaan zakat dan wakaf produktif dengan sertifikasi dari Baznas. Berpengalaman dalam pengembangan program wakaf infrastruktur.', en_bio: 'Expert in zakat and productive waqf management with Baznas certification. Experienced in developing infrastructure waqf programs.', image: 'https://images.unsplash.com/photo-1594824476967-48c8b964ac31?w=400&q=80', active: true },
    { id: 'team-8', name: 'Bambang Suryo Prabowo, S.Kom.', en_name: 'Bambang Suryo Prabowo, S.Kom.', role: 'Koordinator IT & Media', en_role: 'IT & Media Coordinator', bio: 'Memimpin transformasi digital Yamindo dan mengelola seluruh kanal media sosial dan komunikasi publik yayasan.', en_bio: 'Leads Yamindo digital transformation and manages all social media channels and public communications.', image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&q=80', active: true },
  ];
  for (const t of extraTeam) await prisma.teamMember.upsert({ where: { id: t.id }, update: t, create: t });

  console.log('Extra data seeded!');
}
main().catch(e => { console.error(e); process.exit(1); }).finally(async () => { await prisma.$disconnect(); });
